/*
 * ZgjidhLojeGUI.java
 *
 * Created on December 25, 2008, 7:03 PM
 */

package tavell;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Enumeration;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.border.Border;
import javax.swing.border.EmptyBorder;
import javax.swing.border.LineBorder;

/**
 *
 * @author  Arbri
 */
public class ZgjidhLojeGUI extends javax.swing.JFrame { 
    
    /** Deklarimi i variableve */
    
    //Do mbajne reference te objekete perkatese te klasa Program.java
    private Lojtar lojtari1;
    private Lojtar lojtari2;
    private AvatarImage avat1;
    private AvatarImage avat2;
    private Loje loja;    
    private Program prog;
    
    /** Creates new form ZgjidhLojeGUI */
    public ZgjidhLojeGUI(Program p) {
        initComponents();
        displayInCenter();
        extraInitComponents();        
        //Selecct default avatars        
        avatar1MouseClicked();
        avatar4MouseClicked();
        //Vendos referencen tek objektet e Program.java
        /*this.lojtari1= l1;
        this.lojtari2 = l2;
        this.avatar1 = av1;
        this.avatar2 = av2;
        this.loja = l;*/
        this.prog = p;
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        zgjidhLojenPanel = new javax.swing.JPanel();
        tavellRd = new javax.swing.JRadioButton();
        burgRd = new javax.swing.JRadioButton();
        qylRd = new javax.swing.JRadioButton();
        teGjithaRd = new javax.swing.JRadioButton();
        lojtaretPanel = new javax.swing.JPanel();
        lojtari1Label = new javax.swing.JLabel();
        lojtari2Label = new javax.swing.JLabel();
        lojtari1Txt = new javax.swing.JTextField();
        lojtari2Txt = new javax.swing.JTextField();
        pikeLabel = new javax.swing.JLabel();
        pikeTxt = new javax.swing.JTextField();
        avatar1Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        avatar2Panel = new javax.swing.JPanel();
        avatar3Panel = new javax.swing.JPanel();
        avatar4Panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        anulloButon = new javax.swing.JButton();
        okButon = new javax.swing.JButton();
        zgjidhParaqitjenPanel = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Zgjidh Lojen");
        setBounds(new java.awt.Rectangle(300, 300, 0, 0));
        setResizable(false);

        mainPanel.setPreferredSize(mainPanel.getPreferredSize());

        zgjidhLojenPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Zgjidh Lojen"));

        buttonGroup1.add(tavellRd);
        tavellRd.setSelected(true);
        tavellRd.setText("Tavell");

        buttonGroup1.add(burgRd);
        burgRd.setText("Burg");

        buttonGroup1.add(qylRd);
        qylRd.setText("Qyl");

        buttonGroup1.add(teGjithaRd);
        teGjithaRd.setText("Te gjitha");

        javax.swing.GroupLayout zgjidhLojenPanelLayout = new javax.swing.GroupLayout(zgjidhLojenPanel);
        zgjidhLojenPanel.setLayout(zgjidhLojenPanelLayout);
        zgjidhLojenPanelLayout.setHorizontalGroup(
            zgjidhLojenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zgjidhLojenPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(zgjidhLojenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teGjithaRd)
                    .addComponent(qylRd)
                    .addComponent(burgRd)
                    .addComponent(tavellRd))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        zgjidhLojenPanelLayout.setVerticalGroup(
            zgjidhLojenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zgjidhLojenPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tavellRd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(burgRd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(qylRd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(teGjithaRd))
        );

        lojtaretPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Lojtaret"));

        lojtari1Label.setText("Lojtari 1:");

        lojtari2Label.setText("Lojtari 2:");

        lojtari1Txt.setText("Lojtari1");

        lojtari2Txt.setText("Lojtari2");

        pikeLabel.setText("Pike:");

        pikeTxt.setText("5");

        javax.swing.GroupLayout avatar1PanelLayout = new javax.swing.GroupLayout(avatar1Panel);
        avatar1Panel.setLayout(avatar1PanelLayout);
        avatar1PanelLayout.setHorizontalGroup(
            avatar1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );
        avatar1PanelLayout.setVerticalGroup(
            avatar1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel1.setText("Avatar:");

        javax.swing.GroupLayout avatar2PanelLayout = new javax.swing.GroupLayout(avatar2Panel);
        avatar2Panel.setLayout(avatar2PanelLayout);
        avatar2PanelLayout.setHorizontalGroup(
            avatar2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );
        avatar2PanelLayout.setVerticalGroup(
            avatar2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout avatar3PanelLayout = new javax.swing.GroupLayout(avatar3Panel);
        avatar3Panel.setLayout(avatar3PanelLayout);
        avatar3PanelLayout.setHorizontalGroup(
            avatar3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );
        avatar3PanelLayout.setVerticalGroup(
            avatar3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout avatar4PanelLayout = new javax.swing.GroupLayout(avatar4Panel);
        avatar4Panel.setLayout(avatar4PanelLayout);
        avatar4PanelLayout.setHorizontalGroup(
            avatar4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );
        avatar4PanelLayout.setVerticalGroup(
            avatar4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        jLabel2.setText("Avatar:");

        javax.swing.GroupLayout lojtaretPanelLayout = new javax.swing.GroupLayout(lojtaretPanel);
        lojtaretPanel.setLayout(lojtaretPanelLayout);
        lojtaretPanelLayout.setHorizontalGroup(
            lojtaretPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lojtaretPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lojtaretPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lojtaretPanelLayout.createSequentialGroup()
                        .addGroup(lojtaretPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lojtari1Label)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(lojtaretPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lojtari1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(lojtaretPanelLayout.createSequentialGroup()
                                .addComponent(avatar1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(avatar2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(lojtaretPanelLayout.createSequentialGroup()
                        .addGroup(lojtaretPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pikeLabel)
                            .addComponent(lojtari2Label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(lojtaretPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pikeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(lojtaretPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(lojtaretPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lojtari2Txt, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                    .addGroup(lojtaretPanelLayout.createSequentialGroup()
                                        .addComponent(avatar3Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(avatar4Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addComponent(jLabel2))
                .addContainerGap())
        );
        lojtaretPanelLayout.setVerticalGroup(
            lojtaretPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lojtaretPanelLayout.createSequentialGroup()
                .addGroup(lojtaretPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lojtari1Label)
                    .addComponent(lojtari1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lojtaretPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(avatar2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(avatar1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lojtaretPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lojtaretPanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lojtari2Label)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(lojtaretPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lojtari2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(lojtaretPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(avatar4Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(avatar3Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lojtaretPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pikeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pikeLabel))
                .addGap(41, 41, 41))
        );

        anulloButon.setText("Anullo");
        anulloButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anulloButonActionPerformed(evt);
            }
        });

        okButon.setText("OK");
        okButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButonActionPerformed(evt);
            }
        });

        zgjidhParaqitjenPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Zgjidh paraqitjen"));
        zgjidhParaqitjenPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Zgjidh Paraqitjen"));

        jCheckBox1.setText("Te vizatuara");

        javax.swing.GroupLayout zgjidhParaqitjenPanelLayout = new javax.swing.GroupLayout(zgjidhParaqitjenPanel);
        zgjidhParaqitjenPanel.setLayout(zgjidhParaqitjenPanelLayout);
        zgjidhParaqitjenPanelLayout.setHorizontalGroup(
            zgjidhParaqitjenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zgjidhParaqitjenPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jCheckBox1)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        zgjidhParaqitjenPanelLayout.setVerticalGroup(
            zgjidhParaqitjenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zgjidhParaqitjenPanelLayout.createSequentialGroup()
                .addComponent(jCheckBox1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(zgjidhParaqitjenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(zgjidhLojenPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lojtaretPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addComponent(anulloButon)
                        .addGap(45, 45, 45)
                        .addComponent(okButon)
                        .addGap(28, 28, 28))))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(zgjidhLojenPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(zgjidhParaqitjenPanel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(lojtaretPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(anulloButon)
                    .addComponent(okButon))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
private void extraInitComponents(){
    //Extra initializations
        javax.swing.GroupLayout avatar1PanelLayout = new javax.swing.GroupLayout(avatar1Panel);
        avatar1Panel.setLayout(avatar1PanelLayout);
        avatar1PanelLayout.setHorizontalGroup(
            avatar1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(avatar1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        avatar1PanelLayout.setVerticalGroup(
            avatar1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(avatar1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        
        javax.swing.GroupLayout avatar2PanelLayout = new javax.swing.GroupLayout(avatar2Panel);
        avatar2Panel.setLayout(avatar2PanelLayout);
        avatar2PanelLayout.setHorizontalGroup(
            avatar2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(avatar2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        avatar2PanelLayout.setVerticalGroup(
            avatar2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(avatar2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout avatar3PanelLayout = new javax.swing.GroupLayout(avatar3Panel);
        avatar3Panel.setLayout(avatar3PanelLayout);
        avatar3PanelLayout.setHorizontalGroup(
            avatar3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(avatar3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        avatar3PanelLayout.setVerticalGroup(
            avatar3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(avatar3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout avatar4PanelLayout = new javax.swing.GroupLayout(avatar4Panel);
        avatar4Panel.setLayout(avatar4PanelLayout);
        avatar4PanelLayout.setHorizontalGroup(
            avatar4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(avatar4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        avatar4PanelLayout.setVerticalGroup(
            avatar4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(avatar4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );   
        
        avatar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                avatar1MouseClicked();
            }            
        });
        
        avatar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                avatar2MouseClicked();
            }            
        });
        
        avatar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                avatar3MouseClicked();
            }            
        });
        
        avatar4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                avatar4MouseClicked();
            }            
        });
}
    
private void okButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButonActionPerformed
    //JOptionPane.showMessageDialog(this, "Loja e zgjedhur: "+getSelected().getText()+" \n Lojtari 1: "+lojtari1Txt.getText()+" \n Lojtari 2: "+lojtari2Txt.getText()+" \n Piket :"+pikeTxt.getText()+"\n Avatar 1: "+choosenAvatar1.getFileName()+"\n Avatar2: "+choosenAvatar2.getFileName());
    prog.setAvatar1(choosenAvatar1);
    prog.setAvatar2(choosenAvatar2);
    this.lojtari1 = new Lojtar(lojtari1Txt.getText(), 1);
    this.lojtari2 = new Lojtar(lojtari2Txt.getText(), 2);
    prog.setLojtari1(this.lojtari1);
    prog.setLojtari2(this.lojtari2);
    Lojtar l [] = {this.lojtari1, this.lojtari2};
    //Percaktimi i paraqitjes (e vizatuar ose jo)
    Program.llojiParaqitjes = this.jCheckBox1.isSelected();
    //Percaktimi se cila loje eshte
    String selectedGame = getSelected().getText();
    if(selectedGame.equalsIgnoreCase("Tavell"))
        prog.setLoja(new Tavell(l,Integer.parseInt(pikeTxt.getText())));
    else if (selectedGame.equalsIgnoreCase("Qyl"))
        prog.setLoja(new Qyl(l,Integer.parseInt(pikeTxt.getText())));
    else if (selectedGame.equalsIgnoreCase("Burg"))
        prog.setLoja(new Burg(l,Integer.parseInt(pikeTxt.getText())));
    else 
        JOptionPane.showMessageDialog(this, "Loja e zgjedhur: "+getSelected().getText()+" \n Lojtari 1: "+lojtari1Txt.getText()+" \n Lojtari 2: "+lojtari2Txt.getText()+" \n Piket :"+pikeTxt.getText()+"\n Avatar 1: "+choosenAvatar1.getFileName()+"\n Avatar2: "+choosenAvatar2.getFileName());    
    this.dispose();
}//GEN-LAST:event_okButonActionPerformed

private void anulloButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anulloButonActionPerformed
    System.exit(0);
}//GEN-LAST:event_anulloButonActionPerformed

private void avatar1MouseClicked() {
    avatar1Panel.setBorder(new LineBorder(Color.black));
    avatar2Panel.setBorder(null);
    choosenAvatar1 = avatar1;
}

private void avatar2MouseClicked() {
    avatar2Panel.setBorder(new LineBorder(Color.black));
    avatar1Panel.setBorder(null);
    choosenAvatar1 = avatar2;
}

private void avatar3MouseClicked() {
    avatar3Panel.setBorder(new LineBorder(Color.black));
    avatar4Panel.setBorder(null);
    choosenAvatar2 = avatar3;
}

private void avatar4MouseClicked() {
    avatar4Panel.setBorder(new LineBorder(Color.black));
    avatar3Panel.setBorder(null);
    choosenAvatar2 = avatar4;
}

private JRadioButton getSelected() {
    for (Enumeration e = buttonGroup1.getElements() ; e.hasMoreElements() ;) {
         JRadioButton tmp = (JRadioButton)e.nextElement();
         if(tmp.isSelected()) {
            return tmp;            
         }
    }
    return null;   
}

private void displayInCenter(){
    final java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize() ;
    final int wScreen = screenSize.width ;
    final int hScreen = screenSize.height ;
    
    int w = this.getWidth() ;
    int h = this.getHeight() ;
    this.setLocation((wScreen-w)/2, (hScreen-h)/2) ;

}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anulloButon;
    private javax.swing.JPanel avatar1Panel;
    private javax.swing.JPanel avatar2Panel;
    private javax.swing.JPanel avatar3Panel;
    private javax.swing.JPanel avatar4Panel;
    private javax.swing.JRadioButton burgRd;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel lojtaretPanel;
    private javax.swing.JLabel lojtari1Label;
    private javax.swing.JTextField lojtari1Txt;
    private javax.swing.JLabel lojtari2Label;
    private javax.swing.JTextField lojtari2Txt;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton okButon;
    private javax.swing.JLabel pikeLabel;
    private javax.swing.JTextField pikeTxt;
    private javax.swing.JRadioButton qylRd;
    private javax.swing.JRadioButton tavellRd;
    private javax.swing.JRadioButton teGjithaRd;
    private javax.swing.JPanel zgjidhLojenPanel;
    private javax.swing.JPanel zgjidhParaqitjenPanel;
    // End of variables declaration//GEN-END:variables
    private AvatarImage avatar1= new AvatarImage("male.jpg");    
    private AvatarImage avatar2 = new AvatarImage("female.jpg");    
    private AvatarImage avatar3 = new AvatarImage("male.jpg");
    private AvatarImage avatar4 = new AvatarImage("female.jpg");
    private AvatarImage choosenAvatar1;
    private AvatarImage choosenAvatar2;
}
